#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ $DEBUGMODE == true ]]; then
    set -x
fi

if [[ -z $MASTER_URL ]] && [[ -z $SLAVE_SECRET ]]; then
    exec s6-setuidgid abc /usr/sbin/smokeping --config="/etc/smokeping/config" --nodaemon
else
    echo $SLAVE_SECRET > /config/smokeping_secrets && \
    chown abc:abc /config/smokeping_secrets && \
    chmod 640 /config/smokeping_secrets
    exec s6-setuidgid abc /usr/sbin/smokeping --master-url=$MASTER_URL --cache-dir=/var/smokeping --shared-secret=/config/smokeping_secrets --nodaemon
fi
