#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z $MASTER_URL ]] && [[ -z $SLAVE_SECRET ]]; then
    exec s6-setuidgid abc /usr/sbin/smokeping --config="/etc/smokeping/config" --nodaemon
else
    exec s6-setuidgid abc /usr/sbin/smokeping --master-url=$MASTER_URL --cache-dir=/var/smokeping --shared-secret=$SLAVE_SECRET --nodaemon
fi
